[platformio]
src_dir = firmware/led_diffuser_hybrid

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_port = COM5
lib_deps =
  fastled/FastLED
  bblanchon/ArduinoJson
  h2zero/NimBLE-Arduino
